### ISSUE TITLE
TypeError: cypher is not a function

### ISSUE THREAD

**Issue by bigmontz** [neverstew/cypher-template-strings#1]
The functions seems not be exported correctly.

`import cypher from 'cypher-template-strings'` and `const cypher = require('cypher-template-strings')` are result in `TypeError: cypher is not a function` when ```const query = cypher`some query` ```.

The VS Code auto complete is working fine with the correct typescript types. 

Node version: 16.15.1
Library version: 0.1.2

**Comment by neverstew** [comment]
Hey @bigmontz - thanks for letting me know!

If you want to try the library out in node whilst I look into publishing in better formats you can try

```js
const cypher = require('cypher-template-strings').default;
```
